// <auto-generated/>
using NetAF.Blazor.Classes;
using NetAF.Targets.Html;

namespace NetAF.Blazor.Components
{
    /// <summary>
    /// Provides a component that displays output to a user.
    /// </summary>
    public partial class OutputComponent : INetAFComponent
    {
        #region Fields

        private string frameAsHtml = string.Empty;

        #endregion

        /// <summary>
        /// Update the frame.
        /// </summary>
        /// <param name="frame">The new frame.</param>
        internal async void Update(string frame)
        {
            frameAsHtml = frame;
            await InvokeAsync(StateHasChanged);
        }

        #region Implementation of INetAFComponent

        /// <summary>
        /// Set the adapter.
        /// </summary>
        /// <param name="adapter">The adapter.</param>
        public void SetAdapter(HtmlAdapter adapter)
        {
            // no need to keep a reference to the adapter
        }

        #endregion
    }
}